### ISSUE TITLE
Can there be an approach to terminate the last pod of the previous revision when most pods of new revision is up

### ISSUE THREAD

**Issue by gavrissh** [knative-extensions/serving-progressive-rollout#200]
We noticed a particular scenario with the Knative progressive serving rollout, which we need input on.

We have a cluster with 2 GPUs
Initially, we apply isvc with replicas as 1

```
NAME                         READY STATUS  RESTARTS AGE
predictor-00001-xyz           2/2  Running 0
```

     
Later we update the isvc to have replicas as 2
With the progressive rollout, we noticed it got stuck at this juncture with the traffic being moved to the new revision, but with this stalemate

```
NAME                         READY STATUS  RESTARTS AGE
predictor-00001-xyz           2/2  Running 0     
predictor-00002-abc           0/2  Pending 0     
predictor-00002-xdqq          2/2  Running 0    
``` 

The Knative progressive serving rollout design docs mention this -
`"To keep the total number of replicas for both the old and new revisions remain the same, we can reduce the number for the old revisions before increasing the number for the new revisions. However, this is against the principle of the Knative service to serve the workload with demand."`

Is there any approach where the above scenario can be achieved?

**Comment by houshengbo** [comment]
@gavrishp Thank you for opening this issue.
Per the scenario reducing the number of pods for the old revision before increasing the number of pods for the new revision, we have implemented a strategy called `resourceUtil`. I have not updated the doc yet, since this rollout strategy is still under test, and has some existing bugs as in https://github.com/knative-extensions/serving-progressive-rollout/issues/190 and https://github.com/knative-extensions/serving-progressive-rollout/issues/191. 

One way to run this strategy is to add this annotation into your ksvc/isvc: `rollout.knative.dev/progressive-rollout-strategy: "resourceUtil"`, like
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "test"
  annotations:
    # This is the annotation used to configure whether to enable the progressive rollout.
    rollout.knative.dev/progressive-rollout-enabled: "true"
    # This is the annotation used to configure the rollout strategy.
    rollout.knative.dev/progressive-rollout-strategy: "resourceUtil"
```

**Comment by houshengbo** [comment]
Per the issue you have, I am not sure whether the new revision for your service has fully launched. You can check `route` resource to see if all traffic has been shifted to the new revision. If all traffic is shifted to new, the old revision will scale down ultimately.

**Comment by gavrishp** [comment]
@houshengbo Thanks for your response

In the case above, the second pod of the new revision cannot be created due to resource constraints. There are only 2 GPUs available for utilization, and the old revision still has one pod using 1 GPU. 

Is the suggestion to try out the annotations? 
```
annotations:
   # This is the annotation used to configure whether to enable the progressive rollout.
    rollout.knative.dev/progressive-rollout-enabled: "true"
    # This is the annotation used to configure the rollout strategy.
    rollout.knative.dev/progressive-rollout-strategy: "resourceUtil"
```
