### ISSUE TITLE
Not assigning any traffic to the new revision leading to PA error and termination of the new pods

### ISSUE THREAD

**Issue by houshengbo** [knative-extensions/serving-progressive-rollout#335]
The CR PodAutoscaler reports the error, when the new revision start to pick up traffic:

```
status:
  actualScale: 0
  conditions:
  - lastTransitionTime: "2025-05-02T21:08:04Z"
    message: The target is not receiving traffic.
    reason: NoTraffic
    status: "False"
    type: Active
  - lastTransitionTime: "2025-05-02T21:08:04Z"
    message: The target is not receiving traffic.
    reason: NoTraffic
    status: "False"
    type: Ready
  - lastTransitionTime: "2025-05-02T21:08:34Z"
    message: K8s Service is not ready
    reason: NotReady
    status: Unknown
    type: SKSReady
  - lastTransitionTime: "2025-05-02T21:07:04Z"
    status: "True"
    type: ScaleTargetInitialized
```

The reason could potentially be that the traffic only starts to be assigned to the new revision when there is minimum number of pods running for the new revision. There is a short time of period that the new revision is not assigned any traffic. During that period, it is the first sub-stage of the progressive rollout, we should assign 0% traffic to the new revision.

1.16, 1, 17 and 1.18 all have this issue.
