### ISSUE TITLE
Route traffic percent gets updated for the revision that is not in the ready status

### ISSUE THREAD

**Issue by yuzisun** [knative-extensions/serving-progressive-rollout#83]
Launch a new revision that is in bad state, The route traffic gets split to the new revision that is not ready

```bash
tests-predictor-00003-deployment-7644f8cbb5-cdgt4      2/2     Running            0               24m
tests-predictor-00003-deployment-7644f8cbb5-jwfgh      2/2     Running            0               25m
tests-predictor-00003-deployment-7644f8cbb5-mxmms      2/2     Running            0               24m
tests-predictor-00003-deployment-7644f8cbb5-wlwt2      2/2     Running            0               26m
tests-predictor-00004-deployment-79949866fb-9gt5h      0/2     CrashLoopBackOff   8 (3m19s ago)   19m
```

```yaml
spec:
  traffic:
  - latestRevision: false
    percent: 56
    revisionName: libnlp-bms-tests-predictor-00003
  - configurationName: libnlp-bms-tests-predictor
    latestRevision: true
    percent: 44
```

Rollout orchestrator state 
```yaml
spec:
  initialRevisions:
  - direction: up
    latestRevision: true
    minScale: 4
    percent: 100
    revisionName: libnlp-bms-tests-predictor-00003
    targetReplicas: 3
  stageTargetRevisions:
  - direction: down
    latestRevision: false
    minScale: 4
    percent: 56
    revisionName: libnlp-bms-tests-predictor-00003
    targetReplicas: 3
  - direction: up
    latestRevision: true
    minScale: 4
    percent: 44
    revisionName: libnlp-bms-tests-predictor-00004
    targetReplicas: 1
  targetFinishTime: "2024-02-17T15:39:21Z"
  targetRevisions:
  - latestRevision: true
    minScale: 4
    percent: 100
    revisionName: libnlp-bms-tests-predictor-00004
```
