### ISSUE TITLE
the new revision pods immediately get into Terminating state after bumping from 4 to 40

### ISSUE THREAD

**Issue by yuzisun** [knative-extensions/serving-progressive-rollout#85]
the new revision pods immediately get into Terminating state after bumping from 4 to 40

```bash
libnlp-bms-tests-predictor-00005-deployment-65fcd445d-9z2kk       1/2     Terminating   0          15m
libnlp-bms-tests-predictor-00005-deployment-65fcd445d-ddcdr       1/2     Terminating   0          12m
libnlp-bms-tests-predictor-00005-deployment-65fcd445d-q9s4m       2/2     Terminating   0          14m
libnlp-bms-tests-predictor-00005-deployment-65fcd445d-qhnrj       2/2     Running       0          16m
libnlp-bms-tests-predictor-00006-deployment-8bc558d4c-29rqw       1/2     Terminating   0          25s
libnlp-bms-tests-predictor-00006-deployment-8bc558d4c-5ztrv       1/2     Terminating   0          25s
libnlp-bms-tests-predictor-00006-deployment-8bc558d4c-7n2v7       1/2     Terminating   0          4m24s
libnlp-bms-tests-predictor-00006-deployment-8bc558d4c-8k2nw       1/2     Terminating   0          25s
libnlp-bms-tests-predictor-00006-deployment-8bc558d4c-8lxdx       1/2     Terminating   0          25s
libnlp-bms-tests-predictor-00006-deployment-8bc558d4c-9f78m       1/2     Terminating   0          25s
libnlp-bms-tests-predictor-00006-deployment-8bc558d4c-gmkj5       1/2     Terminating   0          25s
libnlp-bms-tests-predictor-00006-deployment-8bc558d4c-hxrkn       2/2     Running       0          3m2s
libnlp-bms-tests-predictor-00006-deployment-8bc558d4c-k9ql2       1/2     Terminating   0          25s
libnlp-bms-tests-predictor-00006-deployment-8bc558d4c-qbvjx       1/2     Terminating   0          25s
libnlp-bms-tests-predictor-00006-deployment-8bc558d4c-qxsn6       1/2     Terminating   0          25s
libnlp-bms-tests-predictor-00006-deployment-8bc558d4c-tpcqd       1/2     Terminating   0          25s
libnlp-bms-tests-predictor-00006-deployment-8bc558d4c-wftjn       2/2     Terminating   0          105s
libnlp-bms-tests-predictor-00006-deployment-8bc558d4c-zmv56       1/2     Terminating   0          25s
```

The rollout orchestrator thinks the target replica should be 4 instead of 40

```yaml
spec:
  initialRevisions:
  - direction: up
    latestRevision: true
    minScale: 4
    percent: 100
    revisionName: libnlp-bms-tests-predictor-00005
    targetReplicas: 4
  stageTargetRevisions:
  - direction: down
    latestRevision: false
    minScale: 4
    revisionName: libnlp-bms-tests-predictor-00005
    targetReplicas: 0
  - direction: up
    latestRevision: true
    minScale: 40
    percent: 100
    revisionName: libnlp-bms-tests-predictor-00006
    targetReplicas: 4
  targetFinishTime: "2024-02-17T16:08:58Z"
  targetRevisions:
  - latestRevision: true
    minScale: 40
    percent: 100
    revisionName: libnlp-bms-tests-predictor-00006
```

KPA keeps changing between 40 and 1
```bash
sun20@XMQXYYPLW6 juicefs % kubectl get kpa -n s-dsplatform                                        
NAME                                     DESIREDSCALE   ACTUALSCALE   READY     REASON
libnlp-bms-tests-predictor-00001         0              0             False     NoTraffic
libnlp-bms-tests-predictor-00002         0              0             False     NoTraffic
libnlp-bms-tests-predictor-00003         0              0             False     NoTraffic
libnlp-bms-tests-predictor-00004         -1             0             False     NoTraffic
libnlp-bms-tests-predictor-00005         0              0             False     NoTraffic
libnlp-bms-tests-predictor-00006         40             1             Unknown   Queued
dsun20@XMQXYYPLW6 juicefs % kubectl get kpa -n s-dsplatform
NAME                                     DESIREDSCALE   ACTUALSCALE   READY   REASON
libnlp-bms-tests-predictor-00001         0              0             False   NoTraffic
libnlp-bms-tests-predictor-00002         0              0             False   NoTraffic
libnlp-bms-tests-predictor-00003         0              0             False   NoTraffic
libnlp-bms-tests-predictor-00004         -1             0             False   NoTraffic
libnlp-bms-tests-predictor-00005         0              0             False   NoTraffic
libnlp-bms-tests-predictor-00006         1              1             True  
```
